import asyncio
import logging
import time
from typing import TYPE_CHECKING

from shared.constants import SERVER_TICK_RATE

if TYPE_CHECKING:
    from server.server import GameServer
    from server.world import ServerWorld

logger = logging.getLogger(__name__)


class GameLoop:
    def __init__(self, world: "ServerWorld", server: "GameServer"):
        self.world = world
        self.server = server
        self.running = False
        self.tick_rate = SERVER_TICK_RATE
        self.tick_interval = 1.0 / self.tick_rate
        self.last_tick = time.time()
        self.tick_count = 0

    async def run(self):
        self.running = True
        logger.info(f"Game loop started at {self.tick_rate} ticks/second")

        while self.running and self.server.running:
            start_time = time.time()

            await self.tick()

            elapsed = time.time() - start_time
            sleep_time = max(0, self.tick_interval - elapsed)

            if sleep_time > 0:
                await asyncio.sleep(sleep_time)
            else:
                logger.warning(
                    f"Tick took {elapsed:.3f}s, longer than interval {self.tick_interval:.3f}s"
                )

    async def tick(self):
        current_time = time.time()
        delta_time = current_time - self.last_tick
        self.last_tick = current_time
        self.tick_count += 1

        # Update world objects (cleanup expired ones) every 10 seconds
        if self.tick_count % 300 == 0:  # 300 ticks = 10 seconds at 30 TPS
            self.world.update()

        # Send standardized updates every 500ms (15 ticks at 30 TPS)
        if self.tick_count % 15 == 0:
            await self.server.send_client_updates()

    async def _process_ai_tick(self, delta_time: float):
        """Process AI decisions for all agents"""
        try:
            # Get current world state
            world_state = self.world.agents

            # Get vision data for all agents
            vision_data = {}
            for agent_id, agent_data in world_state.items():
                if agent_data.is_alive:
                    visible_entities = self.world.get_visible_agents(
                        agent_id, agent_data.vision_range
                    )
                    vision_data[agent_id] = visible_entities

            # Process AI and get actions
            ai_actions = self.server.ai_system.update_ai_tick(
                world_state, vision_data, delta_time
            )

            # Execute AI-generated actions
            for action in ai_actions:
                await self._execute_ai_action(action)

        except Exception as e:
            logger.error(f"Error in AI tick processing: {e}")

    async def _execute_ai_action(self, action: dict):
        """Execute an action generated by the AI system"""
        action_type = action.get("type")

        if action_type == "damage":
            # Process AI-generated attack
            await self.server.process_damage_action(
                action.get("attacker_id"), action
            )

        elif action_type == "move":
            # Process AI-generated movement
            agent_id = action.get("agent_id")
            if agent_id and agent_id in self.world.agents:
                agent = self.world.agents[agent_id]
                agent.velocity_x = action.get("velocity_x", 0.0)
                agent.velocity_y = action.get("velocity_y", 0.0)
                if "rotation" in action:
                    agent.rotation = action["rotation"]

        else:
            logger.warning(f"Unknown AI action type: {action_type}")

    def stop(self):
        self.running = False
        logger.info("Game loop stopped")
